/*
Run this script on:

Server2012R2\SQLServer2012.AbidosDomingo    -  This database will be modified

to synchronize it with:

Server2012R2\SQLServer2012.AbidosDomingoReal

You are recommended to back up your database before running this script

Script created by SQL Data Compare version 11.1.0 from Red Gate Software Ltd at 18/06/2016 0:38:23

*/
		
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
-- Pointer used for text / image updates. This might not be needed, but is declared here just in case
DECLARE @pv binary(16)

PRINT(N'Add rows to [dbo].[GRID]')
SET IDENTITY_INSERT [dbo].[GRID] ON
INSERT INTO [dbo].[GRID] ([ID_Grid], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [BotoAgruparActivat], [BotoSumatoriActivat], [BotoFiltreActivat], [BotoBusquedaIntermitjaActivat], [Autofit], [RowFilterAction], [ViewStyle], [AllowColMoving], [AllowColSizing], [CellClickAction], [ExpandetAll], [AlternateColor], [HeaderClickAction], [SelectTypeRow], [Acceptar_Botons_Extres], [ID_Usuari], [Titul], [Ajuda]) VALUES (20827, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, 0, 0, 1, 0, 3, 0, 3, 3, 3, 0, 0, 2, 2, 0, 10, N'Informática', NULL)
INSERT INTO [dbo].[GRID] ([ID_Grid], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [BotoAgruparActivat], [BotoSumatoriActivat], [BotoFiltreActivat], [BotoBusquedaIntermitjaActivat], [Autofit], [RowFilterAction], [ViewStyle], [AllowColMoving], [AllowColSizing], [CellClickAction], [ExpandetAll], [AlternateColor], [HeaderClickAction], [SelectTypeRow], [Acceptar_Botons_Extres], [ID_Usuari], [Titul], [Ajuda]) VALUES (20828, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, 0, 0, 1, 0, 3, 0, 3, 3, 3, 0, 0, 2, 2, 0, 10, N'Software', NULL)
SET IDENTITY_INSERT [dbo].[GRID] OFF
PRINT(N'Operation applied to 2 rows out of 37')

PRINT(N'Add rows to [dbo].[GRID_Columna]')
SET IDENTITY_INSERT [dbo].[GRID_Columna] ON
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261201, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'ID_Propuesta_Linea_Informatica', N'ID_Propuesta_Linea_Informatica', 0, 2, 0, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261202, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'ID_Propuesta_Linea', N'ID', 0, 19, 1, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 1, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261203, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'ID_TipoDato', N'ID_TipoDato', 0, 2, 2, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261204, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Valor', N'Valor', 1, 113, 6, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261205, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Valor1', N'Valor1', 1, 86, 7, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261206, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Valor2', N'Valor2', 1, 98, 8, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261207, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor3', N'Valor3', 0, 41, 9, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261208, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor4', N'Valor4', 0, 41, 10, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261209, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor5', N'Valor5', 0, 41, 11, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261210, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor6', N'Valor6', 0, 41, 12, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261211, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor7', N'Valor7', 0, 41, 13, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261212, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor8', N'Valor8', 0, 41, 14, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261213, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Valor9', N'Valor9', 0, 41, 15, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261214, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Usuario', N'Usuario', 1, 146, 4, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261215, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Contraseña', N'Contraseña', 1, 119, 5, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261216, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'Observaciones', N'Observaciones', 1, 143, 16, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261217, N'GRD_Informatica', N'frmPropuesta_Linea', NULL, 0, N'Propuesta_Linea', N'Propuesta_Linea', 0, 93, 17, 0, 1, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261218, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 0, N'TipoDato', N'TipoDato', 1, 157, 3, 1, 0, 0, 0, 1, 1, 10, 0, NULL, 1, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261219, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'ID_Propuesta_Linea_Software', N'ID_Propuesta_Linea_Software', 0, 2, 0, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261220, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'ID_Propuesta_Linea', N'ID', 0, 19, 1, 1, 1, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261221, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'ID_Software', N'ID_Software', 0, 2, 2, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261222, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'NumSerie', N'Nº serie', 1, 140, 5, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261223, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'Usuario', N'Usuario', 1, 141, 6, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261224, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'Contraseña', N'Contraseña', 1, 127, 7, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261225, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'Version', N'Versión', 1, 104, 4, 2, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261226, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'Legal', N'Legal', 1, 55, 8, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 1, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261227, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'CampoAuxiliar1', N'CampoAuxiliar1', 1, 148, 9, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261228, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'CampoAuxiliar2', N'CampoAuxiliar2', 1, 150, 10, 1, 0, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 1, 0, 0, N'', N'', N'')
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261229, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar3', N'CampoAuxiliar3', 0, 92, 11, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261230, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar4', N'CampoAuxiliar4', 0, 92, 12, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261231, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar5', N'CampoAuxiliar5', 0, 92, 13, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261232, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar6', N'CampoAuxiliar6', 0, 92, 14, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261233, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar7', N'CampoAuxiliar7', 0, 92, 15, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261234, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar8', N'CampoAuxiliar8', 0, 92, 16, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261235, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'CampoAuxiliar9', N'CampoAuxiliar9', 0, 92, 17, 1, 1, 0, 0, 0, 1, 10, 1, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261236, N'GRD_Software', N'frmPropuesta_Linea', NULL, 0, N'Propuesta_Linea', N'Propuesta_Linea', 0, 93, 18, 0, 1, 0, 0, 0, 1, 10, 0, NULL, 0, 100, 0, 0, 0, NULL, NULL, NULL)
INSERT INTO [dbo].[GRID_Columna] ([ID_Grid_Columna], [Grid_Name], [Formulari_name], [Formulari_AccessibleName], [Banda_Index], [Columna_Key], [Columna_Caption], [Columna_Visible], [Columna_Width], [Columna_Position], [Columna_Alineacio], [Columna_PerformAutoResize], [Columna_No_Permetre_Buscar], [Columna_Aplicar_Colors], [Columna_Busqueda_Inici], [Banda_ColHeadersVisible], [ID_Usuari], [ID_Grid_Columna_Format], [Columna_Color], [Columna_Requerido], [Columna_Nivell_Seguretat], [Columna_Ordenacion], [Columna_Sumatori], [Columna_ComboSeleccioPrimerItem], [Idioma1], [Idioma2], [Idioma3]) VALUES (261237, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 0, N'Software', N'Software', 1, 204, 3, 1, 0, 0, 0, 1, 1, 10, 0, NULL, 1, 100, 1, 0, 0, N'', N'', N'')
SET IDENTITY_INSERT [dbo].[GRID_Columna] OFF
PRINT(N'Operation applied to 37 rows out of 4551')

PRINT(N'Add rows to [dbo].[GRID_ToolGrid_Tools]')
SET IDENTITY_INSERT [dbo].[GRID_ToolGrid_Tools] ON
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13569, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 10, N'Editar', 0)
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13570, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 10, N'Visualizar', 0)
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13571, N'GRD_INFORMATICA', N'FRMPROPUESTA_LINEA', NULL, 10, N'Actualizar', 0)
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13572, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 10, N'Editar', 0)
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13573, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 10, N'Visualizar', 0)
INSERT INTO [dbo].[GRID_ToolGrid_Tools] ([ID_Grid_ToolGrid_Tools], [Grid_Name], [Formulari_Name], [Formulari_AccessibleName], [ID_Usuari], [ToolKey], [Visible]) VALUES (13574, N'GRD_SOFTWARE', N'FRMPROPUESTA_LINEA', NULL, 10, N'Actualizar', 0)
SET IDENTITY_INSERT [dbo].[GRID_ToolGrid_Tools] OFF
PRINT(N'Operation applied to 6 rows out of 134')

PRINT(N'Add rows to [dbo].[Maestro]')
INSERT INTO [dbo].[Maestro] ([ID_Maestro], [Tabla], [Descripcion], [Interna]) VALUES (128, N'Cliente_DireccionTipo', N'Mantenimiento de los tipos de direcciones de un cliente', 0)
INSERT INTO [dbo].[Maestro] ([ID_Maestro], [Tabla], [Descripcion], [Interna]) VALUES (129, N'Software', N'Mantenimiento de software', 0)
INSERT INTO [dbo].[Maestro] ([ID_Maestro], [Tabla], [Descripcion], [Interna]) VALUES (130, N'TipoDato', N'Mantenimiento de tipos de dato', 0)
PRINT(N'Operation applied to 2 rows out of 2')

PRINT(N'Add rows to [dbo].[Software]')
SET IDENTITY_INSERT [dbo].[Software] ON
INSERT INTO [dbo].[Software] ([ID_Software], [Descripcion]) VALUES (1, N'Windows')
INSERT INTO [dbo].[Software] ([ID_Software], [Descripcion]) VALUES (2, N'Office')
SET IDENTITY_INSERT [dbo].[Software] OFF
PRINT(N'Operation applied to 2 rows out of 2')

PRINT(N'Add row to [dbo].[TipoDato]')
SET IDENTITY_INSERT [dbo].[TipoDato] ON
INSERT INTO [dbo].[TipoDato] ([ID_TipoDato], [Descripcion]) VALUES (1, N'Contraseña web')
SET IDENTITY_INSERT [dbo].[TipoDato] OFF
COMMIT TRANSACTION
GO